name: joycai_image_ai_toolkits
description: "A powerful cross-platform AI image toolkit for batch processing, prompt optimization, and LLM-powered image analysis."
publish_to: 'none'
version: 2.18.0+0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  provider: ^6.1.5
  uuid: ^4.5.3
  file_picker: ^12.0.0-beta.7
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2
  path_provider: ^2.1.6
  path: ^1.9.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  intl: ^0.20.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  package_info_plus: ^10.2.0
  flutter_markdown_plus: ^1.0.11
  flutter_local_notifications: ^22.0.0
  desktop_drop: ^0.7.1
  html: ^0.15.6
  crypto: ^3.0.7
  share_plus: ^13.2.0
  image_picker: ^1.2.3
  image_size_getter: ^2.4.1
  gal: ^2.3.2
  image: ^4.9.1
  extended_image: ^10.0.1
  video_player: ^2.11.1
  video_player_win: ^3.2.2
  fc_native_video_thumbnail: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.18.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
    - assets/fonts/
    - assets/presets/prompts/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  windows:
    generate: true
    icon_size: 96 # min:48, max:256, default: 48
  macos:
    generate: true
  web:
    generate: false
    background_color: "#hexcode"
    theme_color: "#hexcode"

msix_config:
  display_name: Joycai Image AI Toolkits
  publisher_display_name: Joycai
  publisher: CN=76DB0498-B398-4C2F-953A-2D26ADD20625
  identity_name: Joycai.JoycaiImageAIToolkits
  logo_path: assets/icon/icon.png
  capabilities: internetClient, privateNetworkClientServer
  install_certificate: false
  sign_msix: true
  languages: en-US,zh-CN
  msix_version: 2.18.0.0
